const metaKeywords = [
  "DSA preparation",
  "Data Structures and Algorithms",
  "SDE interview preparation",
  "Software engineer jobs",
  "Coding interview questions",
  "DSA problem sheets",
  "Engineering notes",
  "Computer science study materials",
  "Technical interview resources",
  "DSA practice problems",
  "Job openings in tech",
  "Programming language notes",
  "DSA sheets by Striver",
  "DSA sheets by Love Babbar",
  "DSA sheets by Nishant Chahar",
  "DSA sheets by Apna College",
  "Blind 75 DSA Sheet",
  "Neet Code 150 DSA Sheet",
  "Nishant Chahar 151 DSA Sheet",
  "Software engineering careers",
  "LeetCode practice problems",
  "Computer science PDF notes",
  "Interview preparation website",
  "DSA progress tracker",
  "Tech interview guide",
  "DSA learning platform",
  "Coding interview prep",
  "Online coding resources",
  "DSA cheat sheets",
  "Engineering study guides",
  "Career opportunities in software engineering",
];

export default metaKeywords;
